---
- name: Check installed locale
  shell: localectl list-locales | grep {{ shhirose_locale_locale }} | wc -l
  register: installed_locale
  changed_when: false
  when: ansible_distribution_major_version|int >=7

- name: Installe locale
  shell: "localedef -f {{ shhirose_locale_locale | regex_replace('^(.*)\\.(.*)$', '\\2') }} -i {{ shhirose_locale_locale | regex_replace('^(.*)\\.(.*)$', '\\1') }} {{ shhirose_locale_locale }}"
  when: installed_locale.stdout == '0' and ansible_distribution_major_version|int >=7

- name: Check setting locale
  shell: echo $LANG
  register: current_locale
  changed_when: current_locale.stdout != shhirose_locale_locale
  notify: Change locale for RedHat
  when: ansible_distribution_major_version|int >=7

- name: Check setting locale for RHEL v6
  shell: echo $LANG
  register: current_locale
  changed_when: false
  when: ansible_distribution_major_version|int == 6

- name: Setting locale for RHEL v6
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ shhirose_locale_config_files }}"
  when: ansible_distribution_major_version|int == 6 and current_locale.stdout != shhirose_locale_locale
